databases:
  - name: room_reservation_app_8yl8
    databaseName: room_reservation_app_8yl8
    user: nihon_info_department
    region: singapore

services:
  - type: web
    name: room_reservation_app_8yl8
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: room_reservation_app_8yl8
          property: connectionString
      - key: RAILS_MASTER_KEY
        value: <your-rails-master-key>
