default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: your_mysql_username
  password: your_mysql_password
  host: localhost

development:
  <<: *default
  database: your_development_database

test:
  <<: *default
  database: your_test_database

production:
  <<: *default
  database: your_production_database
  username: your_production_username
  password: <%= ENV['YOUR_PRODUCTION_DATABASE_PASSWORD'] %>
  host: your_production_host
  port: your_production_port
